searchTextBox = "//input[@id='lst-ib']"
LoginLink="//a[text()='Sign in']"
superUserId="//input[@placeholder='Email or username' and @type='text']"
superUserPass="//input[@placeholder='Password' and @type='password']"
Login="//input[@id='sgnBt']"
loginError="//span[@id='errf']"